# Name of workflow
name: Node CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [20.x]

    steps:
      # Check-out repository under GitHub workspace
      - uses: actions/checkout@v4

      # Set up Node.js with the specified version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Install dependencies with make
      - run: make install

      # Lint code with ESLint
      - run: make lint

      # Run tests (this step runs the 'test' command from Makefile)
      - run: make test

      # Publish code coverage to Code Climate
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        with:
          coverageCommand: make report # This assumes you have a 'make report' command in your Makefile to generate the coverage report
          coverageLocations: ${{github.workspace}}/coverage/lcov-report/index.html # Adjust this if your report path differs
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }} # Add your Code Climate Test Reporter ID in GitHub Secrets
